"""Add Card multi-language columns

Revision ID: 579d62c71f88
Revises: 
Create Date: 2025-10-03 09:47:43.248919

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '579d62c71f88'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_about_title'), table_name='about')
    op.drop_column('about', 'title')
    op.add_column('cards', sa.Column('title_uz', sa.String(), nullable=True))
    op.add_column('cards', sa.Column('title_ru', sa.String(), nullable=True))
    op.add_column('cards', sa.Column('title_en', sa.String(), nullable=True))
    op.add_column('cards', sa.Column('description_uz', sa.String(), nullable=True))
    op.add_column('cards', sa.Column('description_ru', sa.String(), nullable=True))
    op.add_column('cards', sa.Column('description_en', sa.String(), nullable=True))
    op.drop_index(op.f('ix_cards_title'), table_name='cards')
    op.drop_column('cards', 'title')
    op.drop_column('cards', 'description')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('cards', sa.Column('description', sa.VARCHAR(), nullable=True))
    op.add_column('cards', sa.Column('title', sa.VARCHAR(), nullable=True))
    op.create_index(op.f('ix_cards_title'), 'cards', ['title'], unique=False)
    op.drop_column('cards', 'description_en')
    op.drop_column('cards', 'description_ru')
    op.drop_column('cards', 'description_uz')
    op.drop_column('cards', 'title_en')
    op.drop_column('cards', 'title_ru')
    op.drop_column('cards', 'title_uz')
    op.add_column('about', sa.Column('title', sa.VARCHAR(), nullable=True))
    op.create_index(op.f('ix_about_title'), 'about', ['title'], unique=False)
    # ### end Alembic commands ###
