"""Add is_image column

Revision ID: 6411664928ea
Revises: db5a82998978
Create Date: 2025-11-02 10:37:38.520794

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6411664928ea'
down_revision: Union[str, Sequence[str], None] = 'db5a82998978'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('about', 'description_uz',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('about', 'description_ru',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('about', 'description_en',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.add_column('cards', sa.Column('video_link', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('cards', 'video_link')
    op.alter_column('about', 'description_en',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('about', 'description_ru',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('about', 'description_uz',
               existing_type=sa.VARCHAR(),
               nullable=True)
    # ### end Alembic commands ###
