"""add cascade delete to projects

Revision ID: f624b9a2e887
Revises: 9e6b60f20e5b
Create Date: 2025-10-05 22:38:35.921843

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f624b9a2e887'
down_revision: Union[str, Sequence[str], None] = '9e6b60f20e5b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('about', 'description_uz',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('about', 'description_ru',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('about', 'description_en',
               existing_type=sa.VARCHAR(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('about', 'description_en',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('about', 'description_ru',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('about', 'description_uz',
               existing_type=sa.VARCHAR(),
               nullable=True)
    # ### end Alembic commands ###
